/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Edu.esprit.GUI;

import Edu.esprit.DAO.OffreDAO;

/**
 *
 * @author Elyes
 */
public class consulterOffre extends javax.swing.JFrame {

    /**
     * Creates new form consulterOffre
     */
    public consulterOffre() {
        initComponents();
    }
    public consulterOffre(int id) {
        initComponents();
        lbl_image_offre.setIcon(OffreDAO.getImageOffre(id));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_image_offre = new javax.swing.JLabel();
        lbl_lib_offre = new javax.swing.JLabel();
        lbl_id_offre = new javax.swing.JLabel();
        lbl_dateP_offre = new javax.swing.JLabel();
        lbl_etat_Offre = new javax.swing.JLabel();
        lbl_prest_offre = new javax.swing.JLabel();
        lbl_prix_offre = new javax.swing.JLabel();
        lbl_note_offre = new javax.swing.JLabel();
        btn_fermer_detail_offre = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbl_lib_offre.setText("Libelle Offre : ");

        lbl_id_offre.setText("Identifient :");

        lbl_dateP_offre.setText("Date Post :");

        lbl_etat_Offre.setText("Etat Offre : ");

        lbl_prest_offre.setText("Prestataire :");

        lbl_prix_offre.setText("Prix :");

        lbl_note_offre.setText("Note :");

        btn_fermer_detail_offre.setText("Fermer");
        btn_fermer_detail_offre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_fermer_detail_offreActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_id_offre)
                            .addComponent(lbl_lib_offre)
                            .addComponent(lbl_etat_Offre)
                            .addComponent(lbl_dateP_offre)
                            .addComponent(lbl_prest_offre)
                            .addComponent(lbl_prix_offre)
                            .addComponent(lbl_note_offre)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(lbl_image_offre, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addComponent(btn_fermer_detail_offre)))
                .addContainerGap(114, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_image_offre, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_id_offre)
                .addGap(18, 18, 18)
                .addComponent(lbl_lib_offre)
                .addGap(18, 18, 18)
                .addComponent(lbl_prest_offre)
                .addGap(18, 18, 18)
                .addComponent(lbl_dateP_offre)
                .addGap(18, 18, 18)
                .addComponent(lbl_etat_Offre)
                .addGap(18, 18, 18)
                .addComponent(lbl_prix_offre)
                .addGap(18, 18, 18)
                .addComponent(lbl_note_offre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(btn_fermer_detail_offre)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_fermer_detail_offreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_fermer_detail_offreActionPerformed
        this.dispose();
    }//GEN-LAST:event_btn_fermer_detail_offreActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(consulterOffre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(consulterOffre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(consulterOffre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(consulterOffre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new consulterOffre().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_fermer_detail_offre;
    private javax.swing.JLabel lbl_dateP_offre;
    private javax.swing.JLabel lbl_etat_Offre;
    private javax.swing.JLabel lbl_id_offre;
    private javax.swing.JLabel lbl_image_offre;
    private javax.swing.JLabel lbl_lib_offre;
    private javax.swing.JLabel lbl_note_offre;
    private javax.swing.JLabel lbl_prest_offre;
    private javax.swing.JLabel lbl_prix_offre;
    // End of variables declaration//GEN-END:variables
}
