/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Edu.esprit.GUI;

import Edu.esprit.DAO.ReclamationDAO;
import Edu.esprit.Entities.Reclamation;
import java.awt.BorderLayout;
import java.awt.FlowLayout;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import static javax.swing.JFrame.EXIT_ON_CLOSE;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Aymen
 */
public class InterfaceReclamation extends javax.swing.JFrame// implements ActionListener 
{

    List<Integer> idr = new ArrayList<Integer>();
    public static String idClientRep;
    public static JPanel inter;

    /**
     * Creates new form InterfaceReclamation
     */
    public static JPanel getInterface(){
        InterfaceReclamation tempo= new InterfaceReclamation();
        return tempo.inter;
    }
    public  InterfaceReclamation() /*throws IOException*/ {

        
//        setSize(900, 500);
        /*File file = new File(" ");
        BufferedImage bi = new BufferedImage(900, 500, BufferedImage.TYPE_INT_RGB);
        Graphics2D d = bi.createGraphics();
        Image image;
        try {
            image = ImageIO.read(file);
            d.drawImage(image, 0, 0, 900, 500, null);
        } catch (IOException ex) {
            Logger.getLogger(InterfaceReclamation.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        d.dispose();
        ImageIcon imageIcon = new ImageIcon(bi);
        setContentPane(new JLabel(imageIcon));



//     setSize(399,399);
//    setSize(400,400);*/

        initComponents();
        load();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_interf_rec = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jScrollPane3 = new javax.swing.JScrollPane();
        panel_info_rec = new javax.swing.JTextPane();
        jLabel2 = new javax.swing.JLabel();
        boutton_spprimer = new javax.swing.JToggleButton();
        boutton_reponseMail = new javax.swing.JToggleButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Reclamations:");

        jList1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jList1MousePressed(evt);
            }
        });
        jScrollPane2.setViewportView(jList1);

        jScrollPane3.setViewportView(panel_info_rec);

        jLabel2.setText("Inoformation de la reclamation:");

        boutton_spprimer.setText("Supprimer");
        boutton_spprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boutton_spprimerActionPerformed(evt);
            }
        });

        boutton_reponseMail.setText("Répondre par mail");
        boutton_reponseMail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boutton_reponseMailActionPerformed(evt);
            }
        });

        jButton1.setText("Ajouter");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_interf_recLayout = new javax.swing.GroupLayout(pnl_interf_rec);
        pnl_interf_rec.setLayout(pnl_interf_recLayout);
        pnl_interf_recLayout.setHorizontalGroup(
            pnl_interf_recLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_interf_recLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnl_interf_recLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addGroup(pnl_interf_recLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(pnl_interf_recLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(pnl_interf_recLayout.createSequentialGroup()
                            .addComponent(boutton_spprimer)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(boutton_reponseMail))
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        pnl_interf_recLayout.setVerticalGroup(
            pnl_interf_recLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_interf_recLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnl_interf_recLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(pnl_interf_recLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnl_interf_recLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(boutton_spprimer)
                    .addComponent(boutton_reponseMail)
                    .addComponent(jButton1))
                .addGap(27, 27, 27))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnl_interf_rec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnl_interf_rec, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boutton_reponseMailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boutton_reponseMailActionPerformed
        new InterfaceRepMail().setVisible(true);
//        this.setVisible(false);         // TODO add your handling code here:
    }//GEN-LAST:event_boutton_reponseMailActionPerformed

    private void boutton_spprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boutton_spprimerActionPerformed
        // TODO add your handling code here:
        ReclamationDAO r = new ReclamationDAO();
        Reclamation rec = r.findReclamationByIdRec(idr.get(jList1.getSelectedIndex()));
        r.deleteReclamation(rec.getId_rec());
        load();
        JOptionPane.showMessageDialog(null,"suppression effectuée");
        panel_info_rec.setText("");
    }//GEN-LAST:event_boutton_spprimerActionPerformed

    private void jList1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList1MousePressed
        boutton_spprimer.setEnabled(true);
        boutton_reponseMail.setEnabled(true);
        ReclamationDAO r = new ReclamationDAO();
        Reclamation rec = r.findReclamationByIdRec(idr.get(jList1.getSelectedIndex()));
        panel_info_rec.setText("id: " + rec.getId_rec() + "\n"
                + "sujet : " + rec.getRec_sujet() + "\n"
                + "text de la reclamation: " + rec.getRec_text() + "\n"
                + "date reclamtion : " + rec.getDate_rec() + "\n"
                + "client reclamateur : " + rec.getidClient() + "\n"
                + " offre reclamée : " + rec.getOffre_rec() + "\n"
                +" etat de la reclamation:"+ rec.getEtat());
        idClientRep=rec.getidClient();
        // TODO add your handling code here:
    }//GEN-LAST:event_jList1MousePressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new InterfaceAjoutRec().setVisible(true);
        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfaceReclamation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfaceReclamation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfaceReclamation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfaceReclamation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//                try {
                    new InterfaceReclamation().setVisible(true);
//                } catch (IOException ex) {
//                    Logger.getLogger(InterfaceReclamation.class.getName()).log(Level.SEVERE, null, ex);
//                }
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton boutton_reponseMail;
    private javax.swing.JToggleButton boutton_spprimer;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JList jList1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextPane panel_info_rec;
    private javax.swing.JPanel pnl_interf_rec;
    // End of variables declaration//GEN-END:variables
//
//    @Override
//    public void actionPerformed(ActionEvent e) {
//    }

    public  void load() {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        boutton_spprimer.setEnabled(false);
        boutton_reponseMail.setEnabled(false);
        ReclamationDAO rd = new ReclamationDAO();
        List<Reclamation> reclamations;
        reclamations = new ArrayList<Reclamation>();
        reclamations = rd.DisplayAllReclamation();
        DefaultListModel model;

        model = new DefaultListModel();
        jList1.setModel(model);
        model.clear();

        for (int i = 0; i < reclamations.size(); i++) {

            idr.add(reclamations.get(i).getId_rec());
            model.add(i, reclamations.get(i).getRec_sujet());
        }
    }
}
